version: "3.9"
services:

#DB container
  db:
    container_name: mariadb
    image: mariadb:${DB_ImageTag}
    volumes:
      - ./db_mariadb_volume:/var/lib/mysql
    environment:
      MARIADB_USER: ${DB_User}
      MARIADB_PASSWORD: ${DB_Password}
      MARIADB_DATABASE: ${DB_DBName}
      MARIADB_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_TCP_PORT: ${DB_TCPPORT}
    cpus: 1.0
    mem_limit: 2048m
    mem_reservation: 128m

#Wordpress container
  wp:
    container_name: wordpress
    image: wordpress:${WP_ImageTag}
    volumes:
      - ./wp_volume:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:${DB_TCPPORT}
      WORDPRESS_DB_USER: ${DB_User}
      WORDPRESS_DB_NAME: ${DB_DBName}
      WORDPRESS_DB_PASSWORD: ${DB_Password}
    depends_on:
      - db
    cpus: 2.0
    mem_limit: 1024m
    mem_reservation: 128m

#phpmyadmin container
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:${MyAdm_ImageTag}
    environment:
      PMA_HOST: db:${DB_TCPPORT}
    depends_on:
      - db
    cpus: 0.5
    mem_limit: 256m
    mem_reservation: 64m

#haproxy
  haproxy:
    container_name: haproxy
    image: haproxy:${HAPX_ImageTag}
    volumes:
     - ./HAProxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
     - "80:80"
     - "81:81"
    cpus: 0.5
    mem_limit: 128m
    depends_on:
    - wp
    - phpmyadmin
    
volumes:
  wp_volume: {}
  db_mariadb_volume: {}