version: "3.9"
services:

#First NGINX
  nginx_1:
   container_name: nginx_1
   image: nginx:1.23.2
   volumes:
   - ./config/nginx.conf:/etc/nginx/nginx.conf
   - ./simple_website/index1.html:/var/www/html/index.html

#Second NGINX
  nginx_2:
   container_name: nginx_2
   image: nginx:1.23.2
   volumes:
   - ./config/nginx.conf:/etc/nginx/nginx.conf
   - ./simple_website/index2.html:/var/www/html/index.html

#Third NGINX
  nginx_3:
   container_name: nginx_3
   image: nginx:1.23.2
   volumes:
   - ./config/nginx.conf:/etc/nginx/nginx.conf
   - ./simple_website/index3.html:/var/www/html/index.html
  
#Fourth NGINX
  nginx_4:
   container_name: nginx_4
   image: nginx:1.23.2
   volumes:
   - ./config/nginx.conf:/etc/nginx/nginx.conf
   - ./simple_website/index4.html:/var/www/html/index.html

#HAProxy
  haproxy:
    container_name: haproxy
    image: haproxy:2.6.6
    volumes:
     - ./config/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    depends_on:
     - nginx_1
     - nginx_2
     - nginx_3
     - nginx_4
    ports:
    - 80:80
