version: "3.9"
services:

#First Nginx
  nginx_1:
   container_name: nginx_1
   image: nginx:1.23.2
   volumes:
   - ./config/nginx.conf:/etc/nginx/nginx.conf
   - ./simple_website/index1.html:/var/www/html/index.html
   ports:
   - 81:80

#Third HAProxy
  haproxy:
    container_name: haproxy
    image: haproxy:2.6.6
    volumes:
     - ./config/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    depends_on:
     - nginx_1
    ports:
    - 80:80
