version: "3.9"
services: 
  elastic:
    container_name: elastic
    image: elasticsearch:8.4.3
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_PASS}
    ports:
      - "9200:9200"

  logstash:
    container_name: logstash
    image: bitnami/logstash:7.17.6
    depends_on:
     - elastic
     
  kibana:
    container_name: kibana
    image: kibana:8.4.3
    ports:
      - "5601:5601"
    depends_on:
     - elastic