version: "3.9"
services:
  db:
    container_name: mariadb
    image: mariadb:10.9.3
    volumes:
      - ./db_mariadb_volume:/var/lib/mysql
    environment:
      MARIADB_USER: wp_user
      MARIADB_PASSWORD: password1
      MARIADB_DATABASE: wp_db
      MARIADB_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_TCP_PORT: "4584"
  wp:
    container_name: wordpress
    image: wordpress:php7.4
    volumes:
      - ./wp_volume:/var/www/html
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:4584
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_NAME: wp_db
      WORDPRESS_DB_PASSWORD: password1
    depends_on:
      - db
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:5.2.0
    ports:
     - "8081:80"
    environment:
      PMA_HOST: db:4584
    depends_on:
      - db
    
volumes:
  wp_volume: {}
  db_mariadb_volume: {}