version: "3.9"
services:

#DB container
  db:
    container_name: mariadb
    image: mariadb:10.9.3
    volumes:
      - ./db_mariadb_volume:/var/lib/mysql
    environment:
      MARIADB_USER: wp_user
      MARIADB_PASSWORD: password1
      MARIADB_DATABASE: wp_db
      MARIADB_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_TCP_PORT: "4584"
    cpus: 1.0
    mem_limit: 2048m
    mem_reservation: 128m

#Wordpress container
  wp:
    container_name: wordpress
    image: wordpress:php7.4
    volumes:
      - ./wp_volume:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:4584
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_NAME: wp_db
      WORDPRESS_DB_PASSWORD: password1
    depends_on:
      - db
    cpus: 2.0
    mem_limit: 1024m
    mem_reservation: 128m

#phpmyadmin container
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:5.2.0
    environment:
      PMA_HOST: db:4584
    depends_on:
      - db
    cpus: 0.5
    mem_limit: 256m
    mem_reservation: 64m

#haproxy
  haproxy:
    container_name: haproxy
    image: haproxy:2.7-dev7
    volumes:
     - ./HAProxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
     - "80:80"
     - "81:81"
    cpus: 0.5
    mem_limit: 128m
    depends_on:
    - wp
    - phpmyadmin
    
volumes:
  wp_volume: {}
  db_mariadb_volume: {}